version: '3'

services:

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    expose:
      - 3000
    ports:  
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true